spring.application.name=ms-comparacion-precios
<<<<<<< HEAD
server.port=8089
# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
=======

server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
>>>>>>> 16dc53c (fix de eureka, pruebas unitarias y swagger auth)
