spring:
  application:
    name: ms-comparacion-precios
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: ${SERVER_PORT:8089}

jwt:
  secret: ${JWT_SECRET:constructapp-secret-key-2025-muy-larga-para-seguridad}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

---
spring:
  config:
    activate:
      on-profile: dev
MS_PROVEEDOR_MATERIAL_URL: http://localhost:8083

---
spring:
  config:
    activate:
      on-profile: prod

MS_PROVEEDOR_MATERIAL_URL: http://ms-proveedor-material:8083
