spring.application.name=ms-auth
server.port=8091

spring.datasource.url=jdbc:mysql://localhost:3306/db_ms_auth
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false

jwt.secret=constructapp-secret-key-2025-muy-larga-para-seguridad
jwt.expiration=86400000
# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
