spring.application.name=ms-cotizacion
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/db_ms_cotizacion
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
<<<<<<< HEAD

spring.jpa.open-in-view=false
# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
=======
spring.jpa.open-in-view=false


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


spring.cloud.compatibility-verifier.enabled=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
>>>>>>> 16dc53c (fix de eureka, pruebas unitarias y swagger auth)
